version: '3.0'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashaermolich/nodejs2024q1-service-app
    container_name: nodejs2024q1-service-app
    env_file:
      - .env
    networks:
      - backend_network
    volumes:
      - ./src:/app/src
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    container_name: nodejs2024q1-service-db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - backend_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: 
    driver: local

networks:
  backend_network:
    driver: bridge
    name: backend_network